output_dir_folder: /path/to/storage/files
input_dir_folder: /path/to/data

data_name: cropharvest_multi_train
task_type: classification

training: 
  max_epochs: 1
  batch_size: 128
  emb_dim: 128 
  early_stop_args: 
    min_delta: 0.01
    mode: min
    patience: 5
    verbose: True

  missing_as_aug: False
  
experiment: 
  runs: 10
  mlflow_runs_exp: True 
  preprocess: 
    fillnan: False
    flatten: False
    form: zscore
    input_views: ["S2","S1","weather", "S2VI", "DEM"]
      
view_names: ["S2","S1","weather", "S2VI", "DEM"]
args_forward:
  list_testing_views: [
    ["S2", "S2VI"] , #single-view prediction
    ["S1"] , #single-view prediction
    ["S2", "S2VI", "S1"],
    ["S1","weather", "DEM"] , #everything except S2 
    ["S2", "S2VI", "weather", "DEM"] , #everything except S1
  ]

architecture:
  encoders: 
    model_type: tempcnn
    dropout: 0.2
    kernel_size: 5 #default value: 5
    layer_size: 128 #default value: 128
    n_layers: 2 #default value: 3
    seq_len: 12
  predictive_model:
    n_layers: 1
    layer_size: 128
    dropout: 0.2
    batchnorm: True
