output_dir_folder: /path/to/storage/files
input_dir_folder: /path/to/data
additional_method_name: -tempcnn

data_name: cropharvest_multi_train
task_type: classification

training:
  max_epochs: 1000
  batch_size: 128
  emb_dim: 128
  early_stop_args:
    min_delta: 0.01
    mode: min
    patience: 5
    verbose: True

experiment:
  runs: 10
  mlflow_runs_exp: True
  preprocess:
    fillnan: False
    flatten: False
    form: zscore
    input_views: ["S2","S1","weather", "S2VI", "DEM"]
      
view_names: ["S2_S2VI","S1","weather", "DEM"]

architecture:
  encoders:
    S1:
      model_type: tempcnn
      dropout: 0.2
      kernel_size: 5 #default value: 5
      layer_size: 128 #default value: 128
      n_layers: 2 #default value: 3
      seq_len: 12
    S2_S2VI:
      model_type: tempcnn
      dropout: 0.2
      kernel_size: 5 #default value: 5
      layer_size: 128 #default value: 128
      n_layers: 2 #default value: 3
      seq_len: 12
    weather:
      model_type: tempcnn
      dropout: 0.2
      kernel_size: 5 #default value: 5
      layer_size: 128 #default value: 128
      n_layers: 2 #default value: 3
      seq_len: 12
    DEM:
      model_type: mlp
      n_layers: 1
      layer_size: 128
      dropout: 0.2
      batchnorm: False
  predictive_model:
    n_layers: 1
    layer_size: 128
    dropout: 0.2
    batchnorm: True
